name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory.
      run: cmake -S . -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --parallel

    - name: Format
      # Check clang-formatting rules
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target format-check

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure -j"$(nproc)"
